<?php
// $Id$

/**
 * @file
 * Views Slideshow: SingleFrame is typically used for field views.
 */

/**
 * Implements hook_theme().
 */
function views_slideshow_singleframe_theme($existing, $type, $theme, $path) {
  return array(
    'views_slideshow_singleframe' => array(
      'arguments' => array('view' => NULL, 'options' => array(), 'rows' => array(), 'title' => ''),
      'template' => 'views-slideshow-singleframe',
      'file' => 'views_slideshow_singleframe.theme.inc',
    ),
    'views_slideshow_singleframe_controls' =>array(
      'arguments' => array('id' => '', 'view' => NULL, 'options' => array()),
      'file' => 'views_slideshow_singleframe.theme.inc',
    ),
    'views_slideshow_singleframe_control_previous' =>array(
      'arguments' => array('id' => '', 'view' => NULL, 'options' => array()),
      'file' => 'views_slideshow_singleframe.theme.inc',
    ),
    'views_slideshow_singleframe_control_pause' =>array(
      'arguments' => array('id' => '', 'view' => NULL, 'options' => array()),
      'file' => 'views_slideshow_singleframe.theme.inc',
    ),
    'views_slideshow_singleframe_control_next' =>array(
      'arguments' => array('id' => '', 'view' => NULL, 'options' => array()),
      'file' => 'views_slideshow_singleframe.theme.inc',
    ),
    'views_slideshow_singleframe_pager' => array(
      'arguments' => array('id' => '', 'view' => NULL, 'options' => array()),
      'file' => 'views_slideshow_singleframe.theme.inc',
    ),
    'views_slideshow_singleframe_image_count' => array(
      'arguments' => array('id' => '', 'view' => NULL, 'options' => array()),
      'file' => 'views_slideshow_singleframe.theme.inc',
    ),
    'views_slideshow_singleframe_no_display_section' => array(
      'arguments' => array('view' => NULL, 'rows' => NULL, 'id' => NULL, 'mode' => NULL, 'teaser' => TRUE),
      'file' => 'views_slideshow_singleframe.theme.inc',
    ),    
    'views_slideshow_singleframe_no_display_teaser' => array(
      'arguments' => array('item' => NULL, 'id' => NULL, 'count' => NULL),
      'file' => 'views_slideshow_singleframe.theme.inc',
    ),
  );
}

/**
 * Implements hook_help().
 */
function views_slideshow_singleframe_help($path, $arg) {
  switch ($path) {
    case 'admin/help#views_slideshow_singleframe':
      if (module_exists('advanced_help')) {
        $output = '<p>' . l(t('Click here to view the documentation for Views Slideshow SingleFrame.'),  'admin/advanced_help/views_slideshow_singleframe') . '</p>';
      }
      else {
        $output = '<p>' . t('Views Slideshow SingleFrame help can be found by installing and enabling the !advanced_help',  array('!advanced_help' => l('Advanced Help module', 'http://drupal.org/project/advanced_help'))) . '</p>';
      }
      return $output;
  }
}
