<?php
// $Id$

/**
 * @file
 * Views Slideshow: cycle is typically used for field views.
 */

/**
 * Implements hook_init().
 */
function views_slideshow_cycle_init() {
  // If the jQ module is installed, use that to add the jQuery Cycle plugin.
  // This allows different versions of the plugin to be used.
  $js = FALSE;
  if (module_exists('jq')) {
    $loaded_plugins = jq_plugins();
    if (!empty($loaded_plugins['cycle'])) {
      $js = jq_add('cycle');
    }
  }

  // Otherwise, we'll add the version included with this module.
  if (!$js) {
    drupal_add_js(drupal_get_path('module', 'views_slideshow') . '/js/jquery.cycle.all.min.js');
  }

  $module_path = drupal_get_path('module', 'views_slideshow_cycle');
  drupal_add_js($module_path . '/views_slideshow_cycle.js', 'module');
  drupal_add_css($module_path . '/views_slideshow_cycle.css', 'module');
}

/**
 * Implements hook_theme().
 */
function views_slideshow_cycle_theme($existing, $type, $theme, $path) {
  return array(
    'views_slideshow_cycle' => array(
      'arguments' => array('view' => NULL, 'options' => array(), 'rows' => array(), 'title' => ''),
      'template' => 'theme/views-slideshow-cycle',
      'file' => 'theme/views_slideshow_cycle.theme.inc',
    ),
    'views_slideshow_cycle_controls' => array(
      'arguments' => array('vss_id' => '', 'view' => NULL, 'options' => array()),
      'template' => 'theme/views-slideshow-cycle-controls',
      'file' => 'theme/views_slideshow_cycle.theme.inc',
    ),
    'views_slideshow_cycle_control_previous' => array(
      'arguments' => array('vss_id' => '', 'view' => NULL, 'options' => array()),
      'template' => 'theme/views-slideshow-cycle-control-previous',
      'file' => 'theme/views_slideshow_cycle.theme.inc',
    ),
    'views_slideshow_cycle_control_pause' => array(
      'arguments' => array('vss_id' => '', 'view' => NULL, 'options' => array()),
      'template' => 'theme/views-slideshow-cycle-control-pause',
      'file' => 'theme/views_slideshow_cycle.theme.inc',
    ),
    'views_slideshow_cycle_control_next' => array(
      'arguments' => array('vss_id' => '', 'view' => NULL, 'options' => array()),
      'template' => 'theme/views-slideshow-cycle-control-next',
      'file' => 'theme/views_slideshow_cycle.theme.inc',
    ),
    'views_slideshow_cycle_pager' => array(
      'arguments' => array('vss_id' => '', 'view' => NULL, 'options' => array()),
      'file' => 'theme/views_slideshow_cycle.theme.inc',
    ),
    'views_slideshow_cycle_pager_numbered' => array(
      'arguments' => array('view' => NULL, 'attributes' => NULL, 'options' => array()),
      'template' => 'theme/views-slideshow-cycle-pager-numbered',
      'file' => 'theme/views_slideshow_cycle.theme.inc',
    ),
    'views_slideshow_cycle_pager_thumbnails' => array(
      'arguments' => array('view' => NULL, 'attributes' => NULL, 'options' => array()),
      'template' => 'theme/views-slideshow-cycle-pager-thumbnails',
      'file' => 'theme/views_slideshow_cycle.theme.inc',
    ),
    'views_slideshow_cycle_pager_field' => array(
      'arguments' => array('view' => NULL, 'attributes' => NULL, 'options' => array()),
      'template' => 'theme/views-slideshow-cycle-pager-field',
      'file' => 'theme/views_slideshow_cycle.theme.inc',
    ),
    'views_slideshow_cycle_pager_field_field' => array(
      'arguments' => array('view' => NULL, 'field' => NULL, 'count' => NULL),
      'template' => 'theme/views-slideshow-cycle-pager-field-field',
      'file' => 'theme/views_slideshow_cycle.theme.inc',
    ),
    'views_slideshow_cycle_pager_field_item' => array(
      'arguments' => array('item' => NULL, 'vss_id' => NULL, 'count' => NULL),
      'template' => 'theme/views-slideshow-cycle-pager-field-item',
      'file' => 'theme/views_slideshow_cycle.theme.inc',
    ),
    'views_slideshow_cycle_slide_counter' => array(
      'arguments' => array('vss_id' => '', 'view' => NULL, 'options' => array()),
      'template' => 'theme/views-slideshow-cycle-slide-counter',
      'file' => 'theme/views_slideshow_cycle.theme.inc',
    ),
    'views_slideshow_cycle_main_frame' => array(
      'arguments' => array('view' => NULL, 'rows' => NULL, 'vss_id' => NULL, 'mode' => NULL),
      'template' => 'theme/views-slideshow-cycle-main-frame',
      'file' => 'theme/views_slideshow_cycle.theme.inc',
    ),    
    'views_slideshow_cycle_main_frame_row' => array(
      'arguments' => array('items' => NULL, 'vss_id' => NULL, 'count' => NULL),
      'template' => 'theme/views-slideshow-cycle-main-frame-row',
      'file' => 'theme/views_slideshow_cycle.theme.inc',
    ),
    'views_slideshow_cycle_main_frame_row_item' => array(
      'arguments' => array('item' => NULL, 'item_count' => NULL),
      'template' => 'theme/views-slideshow-cycle-main-frame-row-item',
      'file' => 'theme/views_slideshow_cycle.theme.inc',
    ),
  );
}

/**
 * Implements hook_help().
 */
function views_slideshow_cycle_help($path, $arg) {
  switch ($path) {
    case 'admin/help#views_slideshow_cycle':
      if (module_exists('advanced_help')) {
        $output = '<p>' . l(t('Click here to view the documentation for Views Slideshow Cycle.'),  'admin/advanced_help/views_slideshow_cycle') . '</p>';
      }
      else {
        $output = '<p>' . t('Views Slideshow Cycle help can be found by installing and enabling the !advanced_help',  array('!advanced_help' => l('Advanced Help module', 'http://drupal.org/project/advanced_help'))) . '</p>';
      }
      return $output;
  }
}

/**
 * Implementation of hook_views_cycle_skins().
 */
function views_slideshow_cycle_views_slideshow_cycle_skins() {
  $skins['default'] = array(
    'title' => t('Default'),
  );

  return $skins;
}
