<?php

/**
 * @file
 * Views Slideshow: cycle is typically used for field views.
 */

/**
 * Implements hook_theme().
 */
function views_slideshow_cycle_theme($existing, $type, $theme, $path) {
  return array(
    'views_slideshow_cycle' => array(
      'variables' => array('view' => NULL, 'settings' => array(), 'rows' => array(), 'title' => ''),
      'template' => 'theme/views-slideshow-cycle',
      'file' => 'theme/views_slideshow_cycle.theme.inc',
      'pattern' => 'views_slideshow_cycle__',
    ),
    'views_slideshow_cycle_main_frame' => array(
      'variables' => array('vss_id' => NULL, 'view' => NULL, 'settings' => NULL, 'rows' => NULL),
      'template' => 'theme/views-slideshow-cycle-main-frame',
      'pattern' => 'views_slideshow_cycle_main_frame__',
    ),
    'views_slideshow_cycle_main_frame_row' => array(
      'variables' => array('vss_id' => NULL, 'items' => NULL, 'count' => NULL, 'view' => NULL),
      'template' => 'theme/views-slideshow-cycle-main-frame-row',
      'pattern' => 'views_slideshow_cycle_main_frame_row__',
    ),
    'views_slideshow_cycle_main_frame_row_item' => array(
      'variables' => array('item' => NULL, 'item_count' => NULL, 'count' => NULL, 'view' => NULL, 'length' => NULL),
      'template' => 'theme/views-slideshow-cycle-main-frame-row-item',
      'views_slideshow_cycle_main_frame_row_item__',
    ),
  );
}

/**
 * Implements hook_library_info().
 */
 function views_slideshow_cycle_library_info(){
   $libraries['cycle'] = array(
     'name' => 'jQuery Cycle Plugin',
     'website' => 'http://jquery.malsup.com/cycle/',
     'download url' => 'http://jquery.malsup.com/cycle/download.html',
     'version' => '3.0.3',
     'js' => array(
       backdrop_get_path('module', 'views_slideshow_cycle') . '/libraries/jquery.cycle/jquery.cycle.all.js' => array(),
     ),
   );
   return $libraries;
 }


/**
 * Need to have preprocess functions here because drupal doesn't cache them
 * correctly in the theme.inc file.
 *
 * If you would like to override the preprocess functions make sure to look at
 * the associated function in theme.inc.
 */

// Trying to make sure the theme.inc get's loaded.
module_load_include('inc', 'views_slideshow_cycle', 'theme/views_slideshow_cycle.theme');
module_load_include('inc', 'views_slideshow_cycle', 'views_slideshow_cycle.views_slideshow');

function template_preprocess_views_slideshow_cycle_main_frame(&$vars) {
  _views_slideshow_cycle_preprocess_views_slideshow_cycle_main_frame($vars);
}

function template_preprocess_views_slideshow_cycle_main_frame_row(&$vars) {
  _views_slideshow_cycle_preprocess_views_slideshow_cycle_main_frame_row($vars);
}

function template_preprocess_views_slideshow_cycle_main_frame_row_item(&$vars) {
  _views_slideshow_cycle_preprocess_views_slideshow_cycle_main_frame_row_item($vars);
}
