<?php
// $Id$

/**
 *  @file
 *  Provides Slideshow style options for Views.
 */

/**
 *  Implement hook_theme().
 */
function views_slideshow_theme($existing, $type, $theme, $path) {
  return array(
    'views_slideshow_main_section' => array(
      'arguments' => array('id' => NULL, 'hidden_elements' => NULL, 'plugin' => NULL),
      'file' => 'views_slideshow.theme.inc',
    ),
  );
}

/**
 *  Implements hook_views_api().
 */
function views_slideshow_views_api() {
  return array(
    'api' => 2.0,
  );
}
