<?php
// $Id$

/**
 *  @file
 *  The Views Slideshow: ThumbnailHover works with node views only.
 *  It adds two parts to the view: the first part is a series of items
 *  displayed as a list, while the second part is either full or teaser.
 *  The slide show will synchronize the two, so that the 'active' item
 *  will correspond to the single full/teaser item. The slide show can
 *  be set to move automatically and/or on mouse hover.
 */

/**
 *  Implements hook_theme().
 */
function views_slideshow_thumbnailhover_theme($existing, $type, $theme, $path) {
  return array(
    'views_slideshow_thumbnailhover' => array(
      'arguments' => array('view' => NULL, 'options' => array(), 'rows' => array(), 'title' => ''),
      'template' => 'views-slideshow-thumbnailhover',
      'file' => 'views_slideshow_thumbnailhover.theme.inc',
    ),
    'views_slideshow_thumbnailhover_controls' =>array(
      'arguments' => array('id' => '', 'view' => NULL, 'options' => array()),
      'file' => 'views_slideshow_thumbnailhover.theme.inc',
    ),
    'views_slideshow_thumbnailhover_control_previous' =>array(
      'arguments' => array('id' => '', 'view' => NULL, 'options' => array()),
      'file' => 'views_slideshow_thumbnailhover.theme.inc',
    ),
    'views_slideshow_thumbnailhover_control_pause' =>array(
      'arguments' => array('id' => '', 'view' => NULL, 'options' => array()),
      'file' => 'views_slideshow_thumbnailhover.theme.inc',
    ),
    'views_slideshow_thumbnailhover_control_next' =>array(
      'arguments' => array('id' => '', 'view' => NULL, 'options' => array()),
      'file' => 'views_slideshow_thumbnailhover.theme.inc',
    ),
    'views_slideshow_thumbnailhover_image_count' => array(
      'arguments' => array('id' => '', 'view' => NULL, 'options' => array()),
      'file' => 'views_slideshow_thumbnailhover.theme.inc',
    ),
    'views_slideshow_thumbnailhover_breakout_teaser' => array(
      'arguments' => array('item' => NULL, 'id' => NULL, 'count' => NULL),
      'file' => 'views_slideshow_thumbnailhover.theme.inc',
    ),
    'views_slideshow_thumbnailhover_no_display_section' => array(
      'arguments' => array('view' => NULL, 'rows' => NULL, 'id' => NULL, 'mode' => NULL, 'teaser' => TRUE),
      'file' => 'views_slideshow_thumbnailhover.theme.inc',
    ),
    'views_slideshow_thumbnailhover_no_display_teaser' => array(
      'arguments' => array('item' => NULL, 'id' => NULL, 'count' => NULL),
      'file' => 'views_slideshow_thumbnailhover.theme.inc',
    ),
    'views_slideshow_thumbnailhover_breakout_teasers' => array(
      'arguments' => array('items' => NULL, 'id' => NULL),
      'file' => 'views_slideshow_thumbnailhover.theme.inc',
    ),
  );
}

